// <auto-generated />
using System;
using Cyberquiz.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyberquiz.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226132551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryModelQuestionModel", b =>
                {
                    b.Property<int>("CategoryIdId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionIdId")
                        .HasColumnType("int");

                    b.HasKey("CategoryIdId", "QuestionIdId");

                    b.HasIndex("QuestionIdId");

                    b.ToTable("CategoryModelQuestionModel");
                });

            modelBuilder.Entity("CategoryModelSubCategoryModel", b =>
                {
                    b.Property<int>("CategoryModelIdId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryIdId")
                        .HasColumnType("int");

                    b.HasKey("CategoryModelIdId", "SubCategoryIdId");

                    b.HasIndex("SubCategoryIdId");

                    b.ToTable("CategoryModelSubCategoryModel");
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.QuestionAnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionIdId");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.SubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.UserResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserResults");
                });

            modelBuilder.Entity("QuestionModelSubCategoryModel", b =>
                {
                    b.Property<int>("QuestionModelIdId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryIdId")
                        .HasColumnType("int");

                    b.HasKey("QuestionModelIdId", "SubCategoryIdId");

                    b.HasIndex("SubCategoryIdId");

                    b.ToTable("QuestionModelSubCategoryModel");
                });

            modelBuilder.Entity("CategoryModelQuestionModel", b =>
                {
                    b.HasOne("Cyberquiz.DAL.Models.CategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoryIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberquiz.DAL.Models.QuestionModel", null)
                        .WithMany()
                        .HasForeignKey("QuestionIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryModelSubCategoryModel", b =>
                {
                    b.HasOne("Cyberquiz.DAL.Models.CategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoryModelIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberquiz.DAL.Models.SubCategoryModel", null)
                        .WithMany()
                        .HasForeignKey("SubCategoryIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.QuestionAnswerModel", b =>
                {
                    b.HasOne("Cyberquiz.DAL.Models.QuestionModel", "QuestionId")
                        .WithMany("QuestionAnswer")
                        .HasForeignKey("QuestionIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionId");
                });

            modelBuilder.Entity("QuestionModelSubCategoryModel", b =>
                {
                    b.HasOne("Cyberquiz.DAL.Models.QuestionModel", null)
                        .WithMany()
                        .HasForeignKey("QuestionModelIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberquiz.DAL.Models.SubCategoryModel", null)
                        .WithMany()
                        .HasForeignKey("SubCategoryIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cyberquiz.DAL.Models.QuestionModel", b =>
                {
                    b.Navigation("QuestionAnswer");
                });
#pragma warning restore 612, 618
        }
    }
}
